### ISSUE TITLE
Cell 78 is throwing ValueError: 'xVec = ' is not in list

### ISSUE THREAD

**Issue by pRosenberger** [cdsousa/IROS2013-Feas-Ident-WAM7#1]
Tried to run the .ipynb file cell after cell, while creating necessary folders in /tmp. Everything worked fine until cell 78 in part "Feasible Parameter Estimation with Ordinary Least Squares (δ⋆)". Propably file missing "$tmpfolder"sdpa_dat/sdpa.out'.

```
sol_fpe_ols_paper = sdpa(objf_fpe_ols, lmis_fpe_ols_paper, variables_fpe_ols)
```

Error code:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-80-f266878bb20a> in <module>()
----> 1 sol_fpe_ols_paper = sdpa(objf_fpe_ols, lmis_fpe_ols_paper, variables_fpe_ols)

<ipython-input-62-cedab2011b9d> in sdpa(objf, lmis, variables)
      8     outfile = get_ipython().getoutput(u'cat "$tmpfolder"sdpa_dat/sdpa.out')
      9 
---> 10     solstart = outfile.index('xVec = ')
     11     print('\n'.join(outfile[:solstart]))
     12 

ValueError: 'xVec = ' is not in list
```

**Comment by cdsousa** [comment]
My bad, this was probably due to a missing SDPA solver parameter file inside `tmp` folder.

I just pushed a new commit including the file. Please clone again and try it.

Be sure you have the SDPA solver installed. Else, you can try using different solvers (which also have their respective dependencies) by calling instead the function `csdp` or `cvxopt_conelp`, or even the ones given in section "SDP Solver Interfaces" of https://github.com/cdsousa/wam7_dyn_ident.

**Comment by pRosenberger** [comment]
Thank you, now it works fine.
